### ISSUE TITLE
How to persist sessions across restarts?

### ISSUE THREAD

**Issue by danepowell** [leonjza/trauth#4]
I have to occasionally restart my Docker cluster when making configuration changes. When I do, Traefik / Trauth seem to lose existing sessions and clients need to re-authenticate to Trauth. Is there a way to make user sessions persist across container restarts? I assume some container directory needs to be mounted as a volume, but I'm not sure what.

Thanks for this great simple package!

**Comment by leonjza** [comment]
Even as the author I share this pain, and it's something I plan on solving soon.

Sessions are only recorded in memory at the moment. I think that's ok. The part that makes older sessions become invalid, I think, is because the [keys used](https://github.com/leonjza/trauth/blob/09d242b2df729a38bc31593f3eea8862622cb5c8/main.go#L143-L144) are regenerated at boot. So, when the service restarts it cant decrypt older ones, and a new auth prompt makes it way to the user.

**Comment by leonjza** [comment]
This ticket was enough to motivate me to just fix it already. Got a few things I want to upgrade/add then I'll do a release.

**Comment by danepowell** [comment]
Awesome, thanks for the quick response!

**Comment by zyfyy** [comment]
Any progress yet?

**Comment by leonjza** [comment]
> Any progress yet?

Been able to configure a static key for a while now, which means after a reboot clients will still have a valid cookie. Checkout the configuration options [here](https://github.com/leonjza/trauth?tab=readme-ov-file#configuration).
